[2024-02-05T23:22:09.117+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: git_repo_dag.list_repo_tags manual__2024-02-05T23:22:04.148663+00:00 [queued]>
[2024-02-05T23:22:09.139+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: git_repo_dag.list_repo_tags manual__2024-02-05T23:22:04.148663+00:00 [queued]>
[2024-02-05T23:22:09.140+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-05T23:22:09.178+0000] {taskinstance.py:2191} INFO - Executing <Task(GithubOperator): list_repo_tags> on 2024-02-05 23:22:04.148663+00:00
[2024-02-05T23:22:09.181+0000] {standard_task_runner.py:60} INFO - Started process 127 to run task
[2024-02-05T23:22:09.187+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'git_repo_dag', 'list_repo_tags', 'manual__2024-02-05T23:22:04.148663+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/git_repo_dag.py', '--cfg-path', '/tmp/tmp_yrez19u']
[2024-02-05T23:22:09.189+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask list_repo_tags
[2024-02-05T23:22:09.352+0000] {task_command.py:423} INFO - Running <TaskInstance: git_repo_dag.list_repo_tags manual__2024-02-05T23:22:04.148663+00:00 [running]> on host b76a52ce58ff
[2024-02-05T23:22:09.509+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='git_repo_dag' AIRFLOW_CTX_TASK_ID='list_repo_tags' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T23:22:04.148663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T23:22:04.148663+00:00'
[2024-02-05T23:22:09.525+0000] {base.py:83} INFO - Using connection ID 'github_default' for task execution.
[2024-02-05T23:22:09.538+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/github/operators/github.py", line 67, in execute
    hook = GithubHook(github_conn_id=self.github_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/github/hooks/github.py", line 47, in __init__
    self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/github/hooks/github.py", line 62, in get_conn
    raise AirflowException("An access token is required to authenticate to GitHub.")
airflow.exceptions.AirflowException: An access token is required to authenticate to GitHub.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/github/operators/github.py", line 79, in execute
    raise AirflowException(f"GitHub operator error: {e}")
airflow.exceptions.AirflowException: GitHub operator error: An access token is required to authenticate to GitHub.
[2024-02-05T23:22:09.543+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=git_repo_dag, task_id=list_repo_tags, execution_date=20240205T232204, start_date=20240205T232209, end_date=20240205T232209
[2024-02-05T23:22:09.575+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task list_repo_tags (GitHub operator error: An access token is required to authenticate to GitHub.; 127)
[2024-02-05T23:22:09.600+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T23:22:09.628+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
